apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deploy
    labels:
        app: myapp
 spec:
     replicas: 1
     selector:
         matchLabels:
              app: myapp
      tamplate:
         matadata:
            labels:
               app: myapp
          spce:
              containers:
              -  name: myapp -pod
                 image:
                 ports:
                 -  containerport: 9091               